
spring:
  application:
    name: eureka-zuul
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/
zuul:
  routes:
    eureka-feign: /api/feign/**
    eureka-ribbon: /api/ribbon/**
  ignored-patterns: /*-feign/hu
server:
  port: 8760
